version: '3.9'

services:
  bot:
    build: .
    container_name: pdf_bot
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_ID=${ADMIN_ID}
